### ISSUE TITLE
CDAUtil.load() or CDAUtil.loadAs() yield error when validating a not consolidated CCD document : MissingResourceException

### ISSUE THREAD

**Issue by naXa777** [mdht/mdht-models#125]
I constantly get `MissingResourceException: The string resource 'ContinuityOfCareDocumentContinuityOfCareDocumentHasInformationRecipient' could not be located` error when trying to load CCD.xml in Spring / Spring Boot environment.

Maven dependencies:
```
<!-- the same as in this POM https://github.com/mdht/mdht-models/blob/develop/examples/org.openhealthtools.mdht.cda.maven.example/pom.xml -->
<!-- plus the following -->

<dependency>
    <groupId>org.openhealthtools.mdht.cda</groupId>
    <artifactId>org.openhealthtools.mdht.uml.cda.ccd</artifactId>
    <version>3.0.0-SNAPSHOT</version>
</dependency>
<dependency>
    <groupId>org.openhealthtools.mdht.cda</groupId>
    <artifactId>org.openhealthtools.mdht.uml.cda.mu2consol</artifactId>
    <version>3.0.0-SNAPSHOT</version>
</dependency>
```

My code
```
import org.eclipse.emf.common.util.Diagnostic;
import org.eclipse.mdht.uml.cda.ClinicalDocument;
import org.eclipse.mdht.uml.cda.util.CDAUtil;
import org.eclipse.mdht.uml.cda.util.ValidationResult;
import org.openhealthtools.mdht.uml.cda.ccd.CCDPackage;
import org.openhealthtools.mdht.uml.cda.ccd.ContinuityOfCareDocument;
...

        CCDPackage.eINSTANCE.eClass();
        ValidationResult result = new ValidationResult();
        FileInputStream fis = ...
        ClinicalDocument clinicalDocument = CDAUtil.load(fis, result);   // Exception is thrown from HERE!
```

Detailed stack trace:
```
java.util.MissingResourceException: The string resource 'ContinuityOfCareDocumentContinuityOfCareDocumentHasInformationRecipient' could not be located
	at org.eclipse.emf.common.util.DelegatingResourceLocator.delegatedGetString(DelegatingResourceLocator.java:480)
	at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:385)
	at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:359)
	at org.openhealthtools.mdht.uml.cda.ccd.operations.ContinuityOfCareDocumentOperations.validateContinuityOfCareDocumentHasInformationRecipient(ContinuityOfCareDocumentOperations.java:830)
	at org.openhealthtools.mdht.uml.cda.ccd.impl.ContinuityOfCareDocumentImpl.validateContinuityOfCareDocumentHasInformationRecipient(ContinuityOfCareDocumentImpl.java:185)
	at org.openhealthtools.mdht.uml.cda.ccd.util.CCDValidator.validateContinuityOfCareDocument_validateContinuityOfCareDocumentHasInformationRecipient(CCDValidator.java:4736)
	at org.openhealthtools.mdht.uml.cda.ccd.util.CCDValidator.validateContinuityOfCareDocument(CCDValidator.java:4525)
	at org.openhealthtools.mdht.uml.cda.ccd.util.CCDValidator.validate(CCDValidator.java:4157)
	at org.eclipse.emf.ecore.util.EObjectValidator.validate(EObjectValidator.java:324)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:108)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.validate(CDAUtil.java:718)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.validate(CDAUtil.java:707)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.performEMFValidation(CDAUtil.java:841)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.load(CDAUtil.java:278)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.load(CDAUtil.java:253)
        ... application frames omitted from the stack trace
```

**Comment by naXa777** [comment]
Yes, you're right. This error occurred for HITSP/C32 file [johnhalamkaccddocument.xml](https://services.bidmc.org/geekdoctor/johnhalamkaccddocument.xml).

**Comment by naXa777** [comment]
I've added HITSP + IHE + CDT dependencies and initialized `HITSPPackage` instead of `CCDPackage` before validation. A stack trace is different but I still get this error. =(

New maven dependencies:

```
<dependency>
    <groupId>org.openhealthtools.mdht.cda</groupId>
    <artifactId>org.openhealthtools.mdht.uml.cda.hitsp</artifactId>
</dependency>

<dependency>
    <groupId>org.openhealthtools.mdht.cda</groupId>
    <artifactId>org.openhealthtools.mdht.uml.cda.ihe</artifactId>
</dependency>

<dependency>
    <groupId>org.openhealthtools.mdht.cda</groupId>
    <artifactId>org.openhealthtools.mdht.uml.cda.cdt</artifactId>
</dependency>
```

Detailed stack trace
```
java.util.MissingResourceException: The string resource 'ContinuityOfCareDocumentContinuityOfCareDocumentHasInformationRecipient' could not be located
	at org.eclipse.emf.common.util.DelegatingResourceLocator.delegatedGetString(DelegatingResourceLocator.java:480)
	at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:385)
	at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:359)
	at org.openhealthtools.mdht.uml.cda.ccd.operations.ContinuityOfCareDocumentOperations.validateContinuityOfCareDocumentHasInformationRecipient(ContinuityOfCareDocumentOperations.java:830)
	at org.openhealthtools.mdht.uml.cda.ccd.impl.ContinuityOfCareDocumentImpl.validateContinuityOfCareDocumentHasInformationRecipient(ContinuityOfCareDocumentImpl.java:185)
	at org.openhealthtools.mdht.uml.cda.ccd.util.CCDValidator.validateContinuityOfCareDocument_validateContinuityOfCareDocumentHasInformationRecipient(CCDValidator.java:4736)
	at org.openhealthtools.mdht.uml.cda.hitsp.util.HITSPValidator.validatePatientSummary(HITSPValidator.java:4297)
	at org.openhealthtools.mdht.uml.cda.hitsp.util.HITSPValidator.validate(HITSPValidator.java:2275)
	at org.eclipse.emf.ecore.util.EObjectValidator.validate(EObjectValidator.java:324)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:108)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.validate(CDAUtil.java:718)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.validate(CDAUtil.java:707)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.performEMFValidation(CDAUtil.java:841)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.load(CDAUtil.java:278)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.load(CDAUtil.java:253)
        ... application frames omitted from the stack trace
```

**Comment by naXa777** [comment]
And I found that error disappears if I don't initialize the HITSP package at all:
```
// org.openhealthtools.mdht.uml.cda.hitsp.HITSPPackage.eINSTANCE.eClass();
```

Without this package loaded the document is validated, but I get `java.lang.ClassCastException: org.eclipse.mdht.uml.cda.impl.ClinicalDocumentImpl cannot be cast to org.openhealthtools.mdht.uml.cda.hitsp.PatientSummary` error later (the document is not recognized as `PatientSummary`).

My code
```
    static {
        //HITSPPackage.eINSTANCE.eClass();
    }

    public static PatientSummary loadC32(InputStream is) throws Exception {
        final ValidationResult result = new ValidationResult();
        final ClinicalDocument clinicalDocument = CDAUtil.load(is, result);
        return (PatientSummary) clinicalDocument;   // Exception is thrown HERE!
    }
```

How to resolve this ?

**Comment by naXa777** [comment]
I'm desperate....

I tried to use MDHT libraries for validating another document that is HL7 CCD (not consolidated) and I got the same error. Please take a look at this sample - [dropbox](https://www.dropbox.com/s/t4tsqzekqjvuaiv/SampleCCDDocument.xml?dl=0), if you need.

Then I tried to specify an expected doc type as 
```
final ClinicalDocument clinicalDocument = CDAUtil.loadAs(is, CCDPackage.eINSTANCE.eClass(), result);
```
and now it's complaining about a different missing resource:
```
java.util.MissingResourceException: The string resource 'CoverageActivityCoverageActivitySequenceNumber' could not be located
	at org.eclipse.emf.common.util.DelegatingResourceLocator.delegatedGetString(DelegatingResourceLocator.java:480)
	at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:385)
	at org.eclipse.emf.common.util.DelegatingResourceLocator.getString(DelegatingResourceLocator.java:359)
	at org.openhealthtools.mdht.uml.cda.ccd.operations.CoverageActivityOperations.validateCoverageActivitySequenceNumber(CoverageActivityOperations.java:194)
	at org.openhealthtools.mdht.uml.cda.ccd.impl.CoverageActivityImpl.validateCoverageActivitySequenceNumber(CoverageActivityImpl.java:69)
	at org.openhealthtools.mdht.uml.cda.ccd.util.CCDValidator.validateCoverageActivity_validateCoverageActivitySequenceNumber(CCDValidator.java:11876)
	at org.openhealthtools.mdht.uml.cda.ccd.util.CCDValidator.validateCoverageActivity(CCDValidator.java:11827)
	at org.openhealthtools.mdht.uml.cda.ccd.util.CCDValidator.validate(CCDValidator.java:4233)
	at org.eclipse.emf.ecore.util.EObjectValidator.validate(EObjectValidator.java:324)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidate(Diagnostician.java:171)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:158)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:181)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.emf.ecore.util.Diagnostician.doValidateContents(Diagnostician.java:185)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:161)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:137)
	at org.eclipse.emf.ecore.util.Diagnostician.validate(Diagnostician.java:108)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.validate(CDAUtil.java:718)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.validate(CDAUtil.java:707)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.performEMFValidation(CDAUtil.java:841)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.load(CDAUtil.java:278)
	at org.eclipse.mdht.uml.cda.util.CDAUtil.loadAs(CDAUtil.java:379)
        ... application frames omitted from the stack trace
```

**Comment by swmuir** [comment]
Paul

looks like the properties file was not committed during the build 

i have a new properties file which fixes the issue but there is some updates to the repository that are in teh works so you will not be able to get the update for a bit

can i post a new jar for CCD so you can use them versus wait for the update build ?

thanks

sean

**Comment by naXa777** [comment]
yes, please! TY for your guidance.

**Comment by naXa777** [comment]
@swmuir The error is still there 😢 I've deployed your libraries to my local Maven repository (I can share a script if anybody needs it) and used them instead the ones available online.

Here's the latest list of project dependencies
```
[INFO] --- maven-dependency-plugin:3.0.2:tree (default-cli) @ CdaParserCLI ---
[INFO] by.naxa.experiment:CdaParserCLI:jar:1.0-SNAPSHOT
[INFO] +- by.naxa.experiment:CdaParser:jar:1.0-SNAPSHOT:compile
[INFO] |  +- org.openhealthtools.mdht.cda:org.openhealthtools.mdht.uml.cda.consol2:jar:3.0.0-SNAPSHOT:compile
[INFO] |  +- org.openhealthtools.mdht.cda:org.openhealthtools.mdht.uml.cda.mu2consol:jar:3.0.0-SNAPSHOT:compile
[INFO] |  +- org.openhealthtools.mdht.cda:org.openhealthtools.mdht.uml.cda.ccd:jar:3.0.0-SNAPSHOT:compile
[INFO] |  +- org.openhealthtools.mdht.cda:org.openhealthtools.mdht.uml.cda.cdt:jar:3.0.0-SNAPSHOT:compile
[INFO] |  +- org.openhealthtools.mdht.cda:org.openhealthtools.mdht.uml.cda.ihe:jar:3.0.0-SNAPSHOT:compile
[INFO] |  +- org.openhealthtools.mdht.cda:org.openhealthtools.mdht.uml.cda.hitsp:jar:3.0.0-SNAPSHOT:compile
[INFO] |  +- org.eclipse.mdht:org.eclipse.mdht.emf.runtime:jar:3.0.0.201708290502:compile
[INFO] |  +- org.eclipse.mdht:org.eclipse.mdht.uml.cda:jar:3.0.0.201708290502:compile
[INFO] |  +- org.eclipse.mdht:org.eclipse.mdht.uml.hl7.datatypes:jar:3.0.0.201708290502:compile
[INFO] |  +- org.eclipse.mdht:org.eclipse.mdht.uml.hl7.rim:jar:3.0.0.201708290502:compile
[INFO] |  +- org.eclipse.mdht:org.eclipse.mdht.uml.hl7.vocab:jar:3.0.0.201708290502:compile
[INFO] |  +- lpg.runtime.java:lpg.runtime.java:jar:2.0.17.v201004271640:compile
[INFO] |  +- org.eclipse.emf.common:org.eclipse.emf.common:jar:2.12.0.v20160420-0247:compile
[INFO] |  +- org.eclipse.emf.ecore:org.eclipse.emf.ecore:jar:2.12.0.v20160420-0247:compile
[INFO] |  +- org.eclipse.emf.ecore.xmi:org.eclipse.emf.ecore.xmi:jar:2.12.0.v20160420-0247:compile
[INFO] |  +- org.eclipse.ocl:org.eclipse.ocl:jar:3.6.0.v20160523-1914:compile
[INFO] |  +- org.eclipse.ocl.common:org.eclipse.ocl.common:jar:1.4.0.v20160521-2033:compile
[INFO] |  +- org.eclipse.ocl.ecore:org.eclipse.ocl.ecore:jar:3.6.0.v20160523-1914:compile
[INFO] |  +- org.eclipse.uml2.common:org.eclipse.uml2.common:jar:2.1.0.v20170227-0935:compile
[INFO] |  +- org.eclipse.uml2.types:org.eclipse.uml2.types:jar:2.0.0.v20170227-0935:compile
[INFO] |  \- com.google.guava:guava:jar:19.0:compile
[INFO] +- org.springframework.boot:spring-boot-starter:jar:1.5.11.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:1.5.11.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-context:jar:4.3.15.RELEASE:compile
[INFO] |  |     +- org.springframework:spring-aop:jar:4.3.15.RELEASE:compile
[INFO] |  |     +- org.springframework:spring-beans:jar:4.3.15.RELEASE:compile
[INFO] |  |     \- org.springframework:spring-expression:jar:4.3.15.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:1.5.11.RELEASE:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-logging:jar:1.5.11.RELEASE:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.1.11:compile
[INFO] |  |  |  \- ch.qos.logback:logback-core:jar:1.1.11:compile
[INFO] |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] |  |  \- org.slf4j:log4j-over-slf4j:jar:1.7.25:compile
[INFO] |  +- org.springframework:spring-core:jar:4.3.15.RELEASE:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.17:runtime
[INFO] +- commons-cli:commons-cli:jar:1.4:compile
[INFO] +- org.slf4j:jcl-over-slf4j:jar:1.7.22:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.22:compile
[INFO] \- org.slf4j:slf4j-jdk14:jar:1.7.22:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by swmuir** [comment]
okay i did have it working only my local 
and sometimes the snapshot under maven gets unpredictable

i will create a version release just to be on the safe side

**Comment by swmuir** [comment]
sorry for the delay - try the following line of code 

System.out.println(CCDPlugin.INSTANCE.getString("CoverageActivityCoverageActivitySequenceNumber"));

if this does not work - attempt to unzip the jar it is pulling in- i do not have the issue after updating

**Comment by swmuir** [comment]
[org.openhealthtools.mdht.uml.cda.ccd-3.0.0-SNAPSHOT-runtime.zip](https://github.com/mdht/mdht-models/files/1919957/org.openhealthtools.mdht.uml.cda.ccd-3.0.0-SNAPSHOT-runtime.zip)

Here is another build to try 

one line of code that will check to see if the property is there 

System.out.println(CCDPlugin.INSTANCE.getString("CoverageActivityCoverageActivitySequenceNumber"));

**Comment by naXa777** [comment]
My priority is document parsing, so I postpone validation for a while. I think I will return to this issue in a week or so.
