### ISSUE TITLE
Running into the following issue, any help is appreciated

### ISSUE THREAD

**Issue by bahusafoo** [mdht/mdht-models#160]
Following steps from here: https://www.spheregen.com/parsing-continuity-of-care-ccd-using-mirth-and-mdht/

Running into the following error when deploying the channel:

[2022-08-05 16:42:17.994]  ERROR  (com.mirth.connect.server.util.javascript.JavaScriptUtil:595): Error executing 92547717-1b69-4bf7-9cb3-a7bf12750293_Deploy script from channel: 92547717-1b69-4bf7-9cb3-a7bf12750293
com.mirth.connect.server.MirthJavascriptTransformerException: CHANNEL:
	CCDA_MDSuiteSOURCE CODE:
	98: function doScript() {99: // This script executes once when the channel is deployed100: // You only have access to the globalMap and globalChannelMap here to persist data101: 102: // Initialize MDHT Clinical Document Package103: org.openhealthtools.mdht.uml.cda.ccd.CCDPackage.eINSTANCE.eClass();104: 105: return; 106: }LINE NUMBER:
	103DETAILS:
	TypeError: Cannot call property eClass in object [JavaPackage org.openhealthtools.mdht.uml.cda.ccd.CCDPackage.eINSTANCE]. It is not a function, it is "object".
	at 92547717-1b69-4bf7-9cb3-a7bf12750293_Deploy:103 (doScript)
	at 92547717-1b69-4bf7-9cb3-a7bf12750293_Deploy:107
	at com.mirth.connect.server.util.javascript.JavaScriptUtil.executeScript(JavaScriptUtil.java:620)
	at com.mirth.connect.server.util.javascript.JavaScriptUtil$3.doCall(JavaScriptUtil.java:419)
	at com.mirth.connect.server.util.javascript.JavaScriptTask.call(JavaScriptTask.java:114)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by swmuir** [comment]
This line org.openhealthtools.mdht.uml.cda.ccd.CCDPackage.eINSTANCE.eClass(); ?
